### ISSUE TITLE
undefined reference to `querystring'

### ISSUE THREAD

**Issue by valenbase** [nyanmisaka/ffmpeg-rockchip#105]
/usr/bin/ld: /usr/lib/libavcodec.a(rkmppdec.o): in function `rkmpp_decode_init':
/home/firefly/dev/ffmpeg/libavcodec/rkmppdec.c:226: undefined reference to `querystring'

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Compilation

`querystring`: https://github.com/nyanmisaka/rk-mirrors/blob/a9fc19e6b906d7cecd6bcefbd45e5e151831d33f/im2d_api/im2d_common.h#L38

Build and install the latest RGA library instead of using the one comes with the vendor image.
