### ISSUE TITLE
The decoding time of a single frame is too long.

### ISSUE THREAD

**Issue by MapleAura** [nyanmisaka/ffmpeg-rockchip#11]
When I calculated the time to decode, I found out the average time  is almost 84ms.

Open the log and find such a problem “Decoder buffer is full”. This happens regardless of whether I export to NV12 format or drm_prime.

![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/149750728/ef2a0043-0271-4308-8e20-4de786a32e05)

This is the test code:
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/149750728/f9fd4ef4-cb66-4527-87f9-4a0172e13260)

**Comment by nyanmisaka** [comment]
Bear in mind that `memcpy` and `Resize` time should not be counted in HW decoding time.

In particular, `av_hwframe_transfer_data()` already includes `memcpy` for AV_PIX_FMT_DRM_PRIME => AV_PIX_FMT_NV12 conversion.

Therefore your code contains redundant `memcpy`.

**Comment by daoan1412** [comment]
I have a similar problem, even without using memcpy and Resize.

**Comment by MapleAura** [comment]
I've counted the cost on several interfaces. ‘av_read_frame’ cost almost 20ms per frame. I send data three times just receive decoded data once. The log message indicates that the queue is full. In other words, the result can only be returned once if the data is read three times and it takes almost 60 ms. According to the information I have observed from the log, it seems that the decoding time is larger than reading time. But from the experiments done by others, if I do not carry out the copy operation (just export drm_prime), the decoding time is only a few ms.

**Comment by nyanmisaka** [comment]
@MapleAura

I did find an issue regarding the high latency. Please try [this patch](https://github.com/nyanmisaka/ffmpeg-rockchip/commit/ddf7cf1d77aa9bbadb30e62b0d824cddaf55cb07) and see if it helps.

**Comment by MapleAura** [comment]
That's great. It works. :)

**Comment by nyanmisaka** [comment]
Closed by e753665
