### ISSUE TITLE
rk3588 bookworm 硬件解码RKMPP

### ISSUE THREAD

**Issue by xiaobao1980** [nyanmisaka/ffmpeg-rockchip#116]
Radxa ROCK 5 ITX (rk3588)   ubuntu noble jammy系统  kodi MPV（--hwdec=rkmpp ）都可以实现4K硬件解码；bookworm 系统不行 Armbian-unofficial_24.8.2_Rock-5-itx_bookworm_edge_6.11.0-rc4_gnome-backported-mesa_desktop.img ；大佬们是bookworm不支持硬件解码还是其它问题？新人多多关照，谢谢！！！

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip#important

> - Rockchip BSP/vendor kernel is necessary, 5.10 and 6.1 are two tested versions.

Mainline kernel doesn't support RKMPP. You need 6.1 or 5.10 kernel versions.
