### ISSUE TITLE
Distribute ffmpeg-rockchip using Docker

### ISSUE THREAD

**Issue by x2q** [nyanmisaka/ffmpeg-rockchip#119]

**Comment by nyanmisaka** [comment]
I don't have the energy to maintain FFmpeg build scripts at the moment, and reinventing the wheel is pointless. You can already build portable FFmpeg binaries and carry them in any Docker image.

https://github.com/BtbN/FFmpeg-Builds
https://github.com/MarcA711/Rockchip-FFmpeg-Builds
