### ISSUE TITLE
Porting to FFMpeg 7.1？

### ISSUE THREAD

**Issue by tongjiang** [nyanmisaka/ffmpeg-rockchip#122]
1. Is there a schedule to porting this feature to ffmpeg 7.1?
2. How to port to ffmpeg 7.1? first use the project to compare with 6.x , find the difference and then port the difference to 7.1？

**Comment by nyanmisaka** [comment]
Planned to do it in 7.1.x, but not now.

**Comment by nyanmisaka** [comment]
@tongjiang https://github.com/nyanmisaka/ffmpeg-rockchip/tree/7.1
