### ISSUE TITLE
android NDK怎么编译改项目

### ISSUE THREAD

**Issue by ShaolinDeng** [nyanmisaka/ffmpeg-rockchip#123]
rkmpp 
使用对应仓库中的 make-Android.bash 编译生了libmpp.so 
rkrga 
使用仓库中cmake-android.bash 也编译OK

ffmpeg-rockchip 怎么编译出适合android的ffmpeg命令？

**Comment by nyanmisaka** [comment]
I don't work on Android, you're on your own.

**Comment by zybao** [comment]
你可以编译Android平台的吗？

**Comment by jnulzl** [comment]
我在Ubuntu24.04上面编译好了android-arm64-v8a

[build_for_android_README.md](https://github.com/user-attachments/files/29842608/build_for_android_README.md)

[ffmpeg-rockchip-android-arm64-v8a.tar.gz](https://github.com/user-attachments/files/29842642/ffmpeg-rockchip-android-arm64-v8a.tar.gz)

**Comment by jnulzl** [comment]
> 我在Ubuntu24.04上面编译好了android-arm64-v8a
> 
> [build_for_android_README.md](https://github.com/user-attachments/files/29842608/build_for_android_README.md)
> 
> [ffmpeg-rockchip-android-arm64-v8a.tar.gz](https://github.com/user-attachments/files/29842642/ffmpeg-rockchip-android-arm64-v8a.tar.gz)

## adb shell验证

<img width="1068" height="1510" alt="Image" src="https://github.com/user-attachments/assets/85ecb070-e77b-47e2-83c3-94cec9481455" />

**Comment by jnulzl** [comment]
我整理了下代码，简化编译流程：
```shell
>>git clone https://github.com/jnulzl/ffmpeg-rockchip-for-Android
>>cd ffmpeg-rockchip-for-Android
>>sudo apt install git cmake ninja-build meson # meson_version should >= 0.59, my tested os is Ubuntu24.04
>>export ANDROID_NDK="Your NDK full path" # 我的是android-ndk-r27c
>>./build_ffmpeg_rockchip_for_android_all.sh
```
编译产物保存在“ffmpeg-rockchip-for-Android/build_install_Android”中

**Comment by jnulzl** [comment]
# RK3588 Android实测结果

**input.mp4分辨率为：1280x720**

## cpu解码 + cpu scale + cpu编码

```shell
ffmpeg -y -c:v h264 -i input.mp4 -vf "scale=w=640:h=480" -c:v h264 -b:v 2M output.mp4
```
<img width="1611" height="944" alt="Image" src="https://github.com/user-attachments/assets/8999d9de-9705-429c-846f-1af68a582708" />

## mpp解码 + cpu scale + mpp编码

```shell
ffmpeg -y -c:v h264_rkmpp -i input.mp4 -vf "scale=w=640:h=480" -c:v h264_rkmpp -b:v 2M output.mp4
```

<img width="1614" height="858" alt="Image" src="https://github.com/user-attachments/assets/8045efca-a164-47bc-896c-7807c3e7c0e7" />

## mpp解码 + rga scale + mpp编码

```shell
ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -i input.mp4 -vf scale_rkrga=w=640:h=480:format=nv12:afbc=1 -c:v h264_rkmpp -b:v 2M -y output.mp4
```

<img width="1631" height="906" alt="Image" src="https://github.com/user-attachments/assets/cad8f774-8031-4d79-b93a-0efa8a150568" />
