### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by gopower** [nyanmisaka/ffmpeg-rockchip#127]
![image](https://github.com/user-attachments/assets/8978b5b5-9c40-4fa1-992d-c922e70a1602)

libavcodec/rkmppdec.c: In function ‘rkmpp_get_coding_type’:
libavcodec/rkmppdec.c:45:44: error: ‘MPP_VIDEO_CodingAV1’ undeclared (first use in this function); did you mean ‘MPP_VIDEO_CodingAVS’?
   45 |     case AV_CODEC_ID_AV1:           return MPP_VIDEO_CodingAV1;
      |                                            ^~~~~~~~~~~~~~~~~~~
      |                                            MPP_VIDEO_CodingAVS
libavcodec/rkmppdec.c:45:44: note: each undeclared identifier is reported only once for each function it appears in
libavcodec/rkmppenc.c: In function ‘rkmpp_get_mpp_fmt_h26x’:
libavcodec/rkmppenc.c:46:37: error: ‘MPP_FMT_YUV444P’ undeclared (first use in this function); did you mean ‘MPP_FMT_YUV444SP’?
   46 |     case AV_PIX_FMT_YUV444P: return MPP_FMT_YUV444P;
      |                                     ^~~~~~~~~~~~~~~
      |                                     MPP_FMT_YUV444SP
libavcodec/rkmppenc.c:46:37: note: each undeclared identifier is reported only once for each function it appears in
libavcodec/rkmppenc.c: In function ‘rkmpp_submit_frame’:
libavcodec/rkmppenc.c:683:9: error: implicit declaration of function ‘mpp_frame_set_fbc_hdr_stride’; did you mean ‘mpp_frame_set_hor_stride’? [-Werror=implicit-function-declaration]
  683 |         mpp_frame_set_fbc_hdr_stride(mpp_frame, hor_stride);

**Comment by nyanmisaka** [comment]
You are using an outdated MPP library, please check the tutorials in the Wiki and update your MPP.

https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Compilation

```
git clone -b jellyfin-mpp --depth=1 https://github.com/nyanmisaka/mpp.git
```

**Comment by sathishNexion** [comment]
<img width="544" alt="Screenshot 2025-01-14 142812" src="https://github.com/user-attachments/assets/3164e324-01df-45de-b76b-61cc437b8610" />
<img width="580" alt="Screenshot 2025-01-14 142740" src="https://github.com/user-attachments/assets/a14cd2db-4c32-4092-819f-2ca95d4a5074" />
<img width="1118" alt="Screenshot 2025-01-14 142705" src="https://github.com/user-attachments/assets/9a2e2d8f-2841-4e61-88a0-d47bde59f8e2" />




I exactly Followed this --> https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Compilation
But i encountered some errors, Friend

I am using rv1126
