### ISSUE TITLE
 'buffer_hwupload': Invalid argument

### ISSUE THREAD

**Issue by tickmoo** [nyanmisaka/ffmpeg-rockchip#130]
下面是我初始化filter的部分代码，看起来是没问题的，device_ref 也有设置，为什么最终跑起来时候，会爆这个错误？
![微信图片_20241118100254](https://github.com/user-attachments/assets/792fc362-0fad-459e-a880-b82993d93aa9)
![微信图片_20241118100306](https://github.com/user-attachments/assets/dd9782e8-1f8c-47bb-af5a-8e232197c272)

以下是错误代码：
![sadasd](https://github.com/user-attachments/assets/fac54053-3a52-42b6-87a6-11ea513d103c)

**Comment by nyanmisaka** [comment]
It should be the lack of setting the hardware context for the filter.

Search `hw` in these codes:

https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_hw.c

https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_filter.c

**Comment by tickmoo** [comment]
> It should be the lack of setting the hardware context for the filter.
> 
> Search `hw` or `filter_hw_device` or `hw_device_for_filter` in these codes:
> 
> https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_hw.c
> 
> https://github.com/FFmpeg/FFmpeg/blob/master/fftools/ffmpeg_filter.c

不使用hwupload 过滤器，仅仅使用vpp_rkrga过滤器可以实现crop和yuv->rgb24的格式转换吗？

**Comment by nyanmisaka** [comment]
Nope. `hwupload` is a must have filter for memory input.

memory ->(hwupload)-> hardware DMA-BUF -> RGA -> ...

**Comment by JianJingGao** [comment]
我跟你一样的情况，你后来怎么弄的？
