### ISSUE TITLE
ERROR: OpenSSL <3.0.0 is incompatible with the gpl

### ISSUE THREAD

**Issue by ageevp** [nyanmisaka/ffmpeg-rockchip#132]
./configure --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga --enable-openssl
ERROR: OpenSSL <3.0.0 is incompatible with the gpl

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by nyanmisaka** [comment]
You can remove `--enable-gpl` to use LGPL and try again.
