### ISSUE TITLE
No such filter: 'drawtext' 

### ISSUE THREAD

**Issue by yuyinw** [nyanmisaka/ffmpeg-rockchip#135]
Hello:
      i   set  --enable-libfreetype --enable-libfontconfig --enable-libfribidi , bus  dot not support drawtext

 ffmpeg version 6.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: -**-prefix=/usr/local --pkg-config-flags=--static --enable-libfreetype --enable-libfontconfig --enable-libfribidi --enable-libdrm --enable-rkmpp --enable-libx264 --enable-nonfree --enable-gpl --enable-shared --enable-pic --enable-version3**

[AVFilterGraph @ 0x558a8a6110] No such filter: 'drawtext'
[vost#0:0/mpeg4 @ 0x558a7714c0] Error initializing a simple filtergraph

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip/blob/abfc47f288d10ea9ea4ff05ea4deea5e153ac709/configure#L232-L235

https://github.com/nyanmisaka/ffmpeg-rockchip/blob/abfc47f288d10ea9ea4ff05ea4deea5e153ac709/configure#L3735-L3736


**libharfbuzz**
