### ISSUE TITLE
[h264_rkmpp @ 0x559f31ec70] Failed to init MPP context: -1

### ISSUE THREAD

**Issue by JianJingGao** [nyanmisaka/ffmpeg-rockchip#136]
Calling mmp test reports an error,Please help me for look look this error,Thanks!

` ffmpeg  -hwaccel rkmpp -i 11.mp4 -c:v h264_rkmpp output_video.mp4
ffmpeg version abfc47f Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
  configuration: --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '11.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2024-10-25T06:02:59.000000Z
  Duration: 00:00:56.00, start: 0.000000, bitrate: 4209 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 16:15 DAR 256:135], 4207 kb/s, 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      creation_time   : 2024-10-25T06:02:59.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[h264_rkmpp @ 0x559f31ec70] Failed to init MPP context: -1
[vist#0:0/h264 @ 0x559f2fa4a0] Error while opening decoder: Generic error in an external library
[vost#0:0/h264_rkmpp @ 0x559f31d170] Error initializing a simple filtergraph
Error opening output file output_video.mp4.
Error opening output files: Generic error in an external library`

` dpkg -l | grep rockchip
ii  gstreamer1.0-rockchip1                    1.14-4ubuntu2.2firefly5                arm64        The Gstreamer plugins for Rockchip platforms.
ii  libdrm-rockchip1:arm64                    2.4.102-5ubuntu1~20.04.1firefly1       arm64        Userspace interface to msm/kgsl kernel DRM services -- runtime
ii  librockchip-mpp-dev                       1.5.0-4ubuntu2.2firefly6               arm64        Media Process Platform
ii  librockchip-mpp1                          1.5.0-4ubuntu2.2firefly6               arm64        Media Process Platform
ii  librockchip-vpu0                          1.5.0-4ubuntu2.2firefly6               arm64        Media Process Platform
ii  libv4l-rkmpp                              1.3.3-2                                arm64        A rockchip-mpp V4L2 wrapper plugin for chromium V4L2 VDA
ii  rockchip-mpp-demos                        1.5.0-4ubuntu2.2firefly6               arm64        Media Process Platform Demos`

` uname -r
5.10.198`

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip#important

* User MUST be granted permission to access these device files.
```
# DRM allocator
/dev/dri

# DMA_HEAP allocator
/dev/dma_heap

# RGA filters
/dev/rga

# MPP codecs
/dev/mpp_service

# Optional, for compatibility with older kernels and socs
/dev/iep
/dev/mpp-service
/dev/vpu_service
/dev/vpu-service
/dev/hevc_service
/dev/hevc-service
/dev/rkvdec
/dev/rkvenc
/dev/vepu
/dev/h265e
```

Or run with sudo
