### ISSUE TITLE
有使用 scale_rkrga进行缩放格式转换的使用方法吗？ 我想在代码中使用

### ISSUE THREAD

**Issue by Fengwu11** [nyanmisaka/ffmpeg-rockchip#137]

**Comment by nyanmisaka** [comment]
There is no trivial example for using hw avfilter here.

You have to refer to [fftools/ffmpeg_filter.c](https://github.com/nyanmisaka/ffmpeg-rockchip/blob/master/fftools/ffmpeg_filter.c) or learn from this one https://github.com/search?q=avfilter_get_by_name%28%22scale_vaapi%22%29+avfilter_get_by_name%28%22scale_cuda%22%29&type=code
