### ISSUE TITLE
build ffmpeg demo link failed

### ISSUE THREAD

**Issue by JianJingGao** [nyanmisaka/ffmpeg-rockchip#139]
Please help me look this
`proc] Executing command: /usr/bin/cmake --build /home/teamhd/workspace/rk-ffmpeg/build --config Debug --target all --
[build] [1/1 100% :: 0.978] Linking CXX executable bin/RK_FFMPEG
[build] FAILED: bin/RK_FFMPEG 
[build] : && /usr/bin/aarch64-linux-gnu-g++  -std=c++11 -Wall -O0 -Wfatal-errors   -pthread -w -g -g  -rdynamic CMakeFiles/RK_FFMPEG.dir/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o CMakeFiles/RK_FFMPEG.dir/main.cpp.o  -o bin/RK_FFMPEG  -Wl,-Bstatic  -lavcodec  -lavformat  -lavutil  -lswscale  -lswresample  -Wl,-Bdynamic  -lz && :
[build] /usr/bin/ld: CMakeFiles/RK_FFMPEG.dir/main.cpp.o: in function `main':
[build] /home/teamhd/workspace/rk-ffmpeg/build/../main.cpp:116: multiple definition of `main'; CMakeFiles/RK_FFMPEG.dir/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:/home/teamhd/workspac 
[build] /usr/bin/ld: (.text.unlikely+0xe0): undefined reference to `aom_codec_av1_dx_algo'
[build] /usr/bin/ld: (.text.unlikely+0xf0): undefined reference to `aom_codec_av1_dx_algo'
[build] /usr/bin/ld: (.text.unlikely+0xf8): undefined reference to `aom_codec_dec_init_ver'
[build] /usr/bin/ld: (.text.unlikely+0x104): undefined reference to `aom_codec_error'
[build] /usr/bin/ld: (.text+0xbb8): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0xbd8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0xc2c): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o): in function `get_content_url.constprop.0':
[build] (.text+0x1508): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x1558): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x1560): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x1570): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x15c0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x15c8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x15d8): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x1628): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x1630): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x1640): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x1690): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x1698): undefined reference to `xmlFree'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o): in function `parse_manifest':
[build] (.text+0x214c): undefined reference to `xmlCheckVersion'
[build] /usr/bin/ld: (.text+0x2164): undefined reference to `xmlReadMemory'
[build] /usr/bin/ld: (.text+0x216c): undefined reference to `xmlDocGetRootElement'
[build] /usr/bin/ld: (.text+0x21d0): undefined reference to `xmlFreeDoc'
[build] /usr/bin/ld: (.text+0x21d4): undefined reference to `xmlCleanupParser'
[build] /usr/bin/ld: (.text+0x21dc): undefined reference to `xmlFreeNode'
[build] /usr/bin/ld: (.text+0x22e0): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2300): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x230c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2360): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2368): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2384): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2494): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x24b0): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x24d4): undefined reference to `xmlCopyNode'
[build] /usr/bin/ld: (.text+0x24e0): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2528): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2550): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2560): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x25a0): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2618): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2640): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x2664): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2668): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2674): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x26a8): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x26e0): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x2710): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x275c): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2810): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2858): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2888): undefined reference to `xmlNewNode'
[build] /usr/bin/ld: (.text+0x2a4c): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2a60): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2a74): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2aac): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2ab0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2ac8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2acc): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2ae0): undefined reference to `xmlFree'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o):(.text+0x2ae4): more undefined references to `xmlFree' follow
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o): in function `parse_manifest':
[build] (.text+0x2b2c): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2b4c): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2bc4): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2bec): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2c04): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x2c24): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x2c70): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2c80): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2c98): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x2ce8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2cf0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2dd8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2de4): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2e04): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x2e74): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2e78): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x2f14): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2f48): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x2fc4): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x300c): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3058): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x305c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x31d0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x31d4): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3210): undefined reference to `xmlFree'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o):(.text+0x3214): more undefined references to `xmlFree' follow
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o): in function `parse_manifest':
[build] (.text+0x3228): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x327c): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3290): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x32a4): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x33bc): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x33c0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x33e4): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x33f8): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x343c): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x345c): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x3484): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3498): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x353c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3548): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x356c): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x358c): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x359c): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x35bc): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x35e0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x35e4): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x361c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3624): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3648): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x367c): undefined reference to `xmlNodeSetContent'
[build] /usr/bin/ld: (.text+0x36f0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x36fc): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3744): undefined reference to `xmlNodeSetContent'
[build] /usr/bin/ld: (.text+0x3790): undefined reference to `xmlNodeGetContent'
[build] /usr/bin/ld: (.text+0x382c): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3868): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x38b0): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3910): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x39b0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x39c0): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3a04): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3a0c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3a4c): undefined reference to `xmlFree'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o):(.text+0x3a50): more undefined references to `xmlFree' follow
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(dashdec.o): in function `parse_manifest':
[build] (.text+0x3b48): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3b70): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x3b90): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x3ba8): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x3bcc): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x3be4): undefined reference to `xmlGetProp'
[build] /usr/bin/ld: (.text+0x3c00): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3c0c): undefined reference to `xmlFree'
[build] /usr/bin/ld: (.text+0x3c20): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x3c40): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x3c7c): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x3c9c): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: (.text+0x3cd4): undefined reference to `xmlFirstElementChild'
[build] /usr/bin/ld: (.text+0x3cf4): undefined reference to `xmlNextElementSibling'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libgme.o): in function `read_seek_gme':
[build] (.text+0x24): undefined reference to `gme_seek'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libgme.o): in function `read_close_gme':
[build] (.text+0x7c): undefined reference to `gme_free_info'
[build] /usr/bin/ld: (.text+0x84): undefined reference to `gme_delete'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libgme.o): in function `read_packet_gme':
[build] (.text+0xd8): undefined reference to `gme_track_ended'
[build] /usr/bin/ld: (.text+0xfc): undefined reference to `gme_play'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libgme.o): in function `read_header_gme':
[build] (.text+0x1dc): undefined reference to `gme_open_data'
[build] /usr/bin/ld: (.text+0x1f8): undefined reference to `gme_track_info'
[build] /usr/bin/ld: (.text+0x208): undefined reference to `gme_start_track'
[build] /usr/bin/ld: (.text+0x290): undefined reference to `gme_track_count'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libgme.o): in function `probe_gme':
[build] (.text+0x4b4): undefined reference to `gme_identify_header'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libopenmpt.o): in function `read_seek_openmpt':
[build] (.text+0x34): undefined reference to `openmpt_module_set_position_seconds'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libopenmpt.o): in function `read_close_openmpt':
[build] (.text+0x84): undefined reference to `openmpt_module_destroy'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libopenmpt.o): in function `read_packet_openmpt':
[build] (.text+0x178): undefined reference to `openmpt_module_read_float_mono'
[build] /usr/bin/ld: (.text+0x1b0): undefined reference to `openmpt_module_read_interleaved_float_quad'
[build] /usr/bin/ld: (.text+0x1cc): undefined reference to `openmpt_module_read_interleaved_float_stereo'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libopenmpt.o): in function `read_header_openmpt':
[build] (.text+0x280): undefined reference to `openmpt_module_create_from_memory2'
[build] /usr/bin/ld: (.text+0x2b0): undefined reference to `openmpt_module_get_num_subsongs'
[build] /usr/bin/ld: (.text+0x2d0): undefined reference to `openmpt_module_select_subsong'
[build] /usr/bin/ld: (.text+0x2e8): undefined reference to `openmpt_module_get_duration_seconds'
[build] /usr/bin/ld: (.text+0x2f8): undefined reference to `openmpt_module_get_metadata'
[build] /usr/bin/ld: (.text+0x310): undefined reference to `openmpt_free_string'
[build] /usr/bin/ld: (.text+0x324): undefined reference to `openmpt_module_get_metadata'
[build] /usr/bin/ld: (.text+0x33c): undefined reference to `openmpt_free_string'
[build] /usr/bin/ld: (.text+0x34c): undefined reference to `openmpt_module_get_metadata'
[build] /usr/bin/ld: (.text+0x364): undefined reference to `openmpt_free_string'
[build] /usr/bin/ld: (.text+0x374): undefined reference to `openmpt_module_get_metadata'
[build] /usr/bin/ld: (.text+0x38c): undefined reference to `openmpt_free_string'
[build] /usr/bin/ld: (.text+0x3a0): undefined reference to `openmpt_module_get_metadata'
[build] /usr/bin/ld: (.text+0x3b8): undefined reference to `openmpt_free_string'
[build] /usr/bin/ld: (.text+0x55c): undefined reference to `openmpt_module_destroy'
[build] /usr/bin/ld: (.text+0x584): undefined reference to `openmpt_module_destroy'
[build] /usr/bin/ld: (.text+0x59c): undefined reference to `openmpt_module_destroy'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(libopenmpt.o): in function `read_probe_openmpt':
[build] (.text+0x6e4): undefined reference to `openmpt_probe_file_header_without_filesize'
[build] /usr/bin/ld: (.text+0x704): undefined reference to `openmpt_is_extension_supported'
[build] /usr/bin/ld: (.text+0x738): undefined reference to `openmpt_is_extension_supported'
[build] /usr/bin/ld: (.text+0x750): undefined reference to `openmpt_probe_file_header_get_recommended_size'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(matroskadec.o): in function `matroska_decode_buffer.isra.0':
[build] (.text+0xa40): undefined reference to `BZ2_bzDecompressInit'
[build] /usr/bin/ld: (.text+0xa74): undefined reference to `BZ2_bzDecompress'
[build] /usr/bin/ld: (.text+0xab0): undefined reference to `BZ2_bzDecompressEnd'
[build] /usr/bin/ld: (.text+0xcb4): undefined reference to `BZ2_bzDecompressEnd'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(spdifdec.o): in function `ff_spdif_read_packet':
[build] (.text+0x224): undefined reference to `av_adts_header_parse'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(spdifdec.o): in function `ff_spdif_probe':
[build] (.text+0x540): undefined reference to `av_adts_header_parse'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavformat.a(spdifenc.o): in function `spdif_header_aac':
[build] (.text+0x6b8): undefined reference to `av_adts_header_parse'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_drm.o): in function `drm_device_create':
[build] (.text+0x6f8): undefined reference to `drmGetVersion'
[build] /usr/bin/ld: (.text+0x72c): undefined reference to `drmFreeVersion'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_frames_uninit':
[build] (.text+0xd48): undefined reference to `clReleaseCommandQueue'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_device_uninit':
[build] (.text+0xdc8): undefined reference to `clReleaseCommandQueue'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_pool_alloc':
[build] (.text+0xe90): undefined reference to `clCreateImage'
[build] /usr/bin/ld: (.text+0xf14): undefined reference to `clReleaseMemObject'
[build] /usr/bin/ld: (.text+0xf20): undefined reference to `clReleaseMemObject'
[build] /usr/bin/ld: (.text+0xf2c): undefined reference to `clReleaseMemObject'
[build] /usr/bin/ld: (.text+0xf38): undefined reference to `clReleaseMemObject'
[build] /usr/bin/ld: (.text+0xf44): undefined reference to `clReleaseMemObject'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o):(.text+0xf50): more undefined references to `clReleaseMemObject' follow
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_frames_init':
[build] (.text+0x10f0): undefined reference to `clRetainCommandQueue'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_device_init':
[build] (.text+0x11c0): undefined reference to `clRetainCommandQueue'
[build] /usr/bin/ld: (.text+0x11e8): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: (.text+0x1228): undefined reference to `clCreateCommandQueue'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_enumerate_devices':
[build] (.text+0x12e0): undefined reference to `clGetDeviceIDs'
[build] /usr/bin/ld: (.text+0x1334): undefined reference to `clGetDeviceIDs'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_enumerate_platforms':
[build] (.text+0x141c): undefined reference to `clGetPlatformIDs'
[build] /usr/bin/ld: (.text+0x145c): undefined reference to `clGetPlatformIDs'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_device_free':
[build] (.text+0x1508): undefined reference to `clReleaseContext'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_get_device_string':
[build] (.text+0x1614): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: (.text+0x1640): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_filter_device':
[build] (.text+0x1830): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_get_platform_string':
[build] (.text+0x19a4): undefined reference to `clGetPlatformInfo'
[build] /usr/bin/ld: (.text+0x19d0): undefined reference to `clGetPlatformInfo'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_frames_get_constraints':
[build] (.text+0x1bf4): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: (.text+0x1c18): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: (.text+0x1c5c): undefined reference to `clGetSupportedImageFormats'
[build] /usr/bin/ld: (.text+0x1cac): undefined reference to `clGetSupportedImageFormats'
[build] /usr/bin/ld: (.text+0x2370): undefined reference to `clGetDeviceInfo'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_device_create':
[build] (.text+0x2750): undefined reference to `clCreateContext'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_unmap_frame':
[build] (.text+0x2998): undefined reference to `clEnqueueUnmapMemObject'
[build] /usr/bin/ld: (.text+0x29d0): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: (.text+0x2a00): undefined reference to `clReleaseEvent'
[build] /usr/bin/ld: (.text+0x2a74): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_transfer_data_from':
[build] (.text+0x2b7c): undefined reference to `clEnqueueReadImage'
[build] /usr/bin/ld: (.text+0x2bbc): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: (.text+0x2bfc): undefined reference to `clReleaseEvent'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_transfer_data_to':
[build] (.text+0x2dac): undefined reference to `clEnqueueWriteImage'
[build] /usr/bin/ld: (.text+0x2dec): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: (.text+0x2e28): undefined reference to `clReleaseEvent'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavutil.a(hwcontext_opencl.o): in function `opencl_map_from':
[build] (.text+0x3038): undefined reference to `clEnqueueMapImage'
[build] /usr/bin/ld: (.text+0x30a8): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: (.text+0x30ec): undefined reference to `clReleaseEvent'
[build] /usr/bin/ld: (.text+0x31a4): undefined reference to `clEnqueueUnmapMemObject'
[build] /usr/bin/ld: (.text+0x31bc): undefined reference to `clWaitForEvents'
[build] /usr/bin/ld: (.text+0x31e8): undefined reference to `clReleaseEvent'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `get_out_samples':
[build] (.text+0x84): undefined reference to `soxr_delay'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `get_delay':
[build] (.text+0x10c): undefined reference to `soxr_delay'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `flush':
[build] (.text+0x194): undefined reference to `soxr_delay'
[build] /usr/bin/ld: (.text+0x1b8): undefined reference to `soxr_process'
[build] /usr/bin/ld: (.text+0x1d8): undefined reference to `soxr_process'
[build] /usr/bin/ld: (.text+0x1e0): undefined reference to `soxr_delay'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `process':
[build] (.text+0x258): undefined reference to `soxr_set_num_channels'
[build] /usr/bin/ld: (.text+0x264): undefined reference to `soxr_set_error'
[build] /usr/bin/ld: (.text+0x2bc): undefined reference to `soxr_process'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `destroy':
[build] (.text+0x304): undefined reference to `soxr_delete'
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libswresample.a(soxr_resample.o): in function `create':
[build] (.text+0x3dc): undefined reference to `soxr_io_spec'
[build] /usr/bin/ld: (.text+0x40c): undefined reference to `soxr_quality_spec'
[build] /usr/bin/ld: (.text+0x440): undefined reference to `soxr_delete'
[build] /usr/bin/ld: (.text+0x460): undefined reference to `soxr_create'
[build] collect2: error: ld returned 1 exit status`

**Comment by JianJingGao** [comment]
I added some dependencies, I reduced some errors, and I still can't find these


`[build] /home/teamhd/workspace/rk-ffmpeg/build/../main.cpp:116: multiple definition of `main'; CMakeFiles/RK_FFMPEG.dir/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:/home/teamhd/workspace/rk-ffmpeg/build/CMakeFiles/3.16.3/CompilerIdCXX/CMakeCXXCompilerId.cpp:638: first defined here
[build] /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/../../../aarch64-linux-gnu/libavcodec.a(rkmppdec.o): in function `rkmpp_decode_init':
[build] /home/teamhd/dev/ffmpeg/libavcodec/rkmppdec.c:283: undefined reference to `querystring'
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.`

**Comment by JianJingGao** [comment]
# 链接 FFmpeg 库到可执行文件
target_link_libraries(RK_FFMPEG


/usr/lib/aarch64-linux-gnu/libavcodec.a
/usr/lib/aarch64-linux-gnu/libavformat.a
/usr/lib/aarch64-linux-gnu/libavutil.a
/usr/lib/aarch64-linux-gnu/libswscale.a
/usr/lib/aarch64-linux-gnu/libswresample.a
${ZLIB_LIBRARIES}  # 链接 zlib 库
${ROCKCHIP_MPP_LIBRARIES}
${LZMA_LIBRARIES}
${LIBDRM_LIBRARIES}
)

**Comment by nyanmisaka** [comment]
These errors are clearly NOT caused by ffmpeg-rockchip. Please learn how to build ffmpeg and fix your build scripts.

**Comment by JianJingGao** [comment]
I solved these problems by adding mpp, rkrgb and other dependencies。
# 链接 FFmpeg 库到可执行文件
target_link_libraries(RK_FFMPEG


/usr/lib/aarch64-linux-gnu/libavcodec.a
/usr/lib/aarch64-linux-gnu/libavformat.a
/usr/lib/aarch64-linux-gnu/libavutil.a
/usr/lib/aarch64-linux-gnu/libswscale.a
/usr/lib/aarch64-linux-gnu/libswresample.a
/home/teamhd/dev/rkrga_build/librga.so
${ZLIB_LIBRARIES}  # 链接 zlib 库
${ROCKCHIP_MPP_LIBRARIES}
${LZMA_LIBRARIES}
${LIBDRM_LIBRARIES}
)
