### ISSUE TITLE
可以在命令行使用rkmpp硬解码，但是无法在代码中使用

### ISSUE THREAD

**Issue by suhao2** [nyanmisaka/ffmpeg-rockchip#145]
ffmpeg -hwaccels显示drm和rkmpp
ffmpeg -decoders | grep “rkmpp”能显示rkmpp的一众解码器
ffmpeg -hwaccels rkmpp能够使用硬解码（已查看mpp资源调用）
但是avcodec_find_decoder_by_name（“h264_rkmpp”）无法找到
遍历所有的decoder，总共666个，没有和rkmpp有关的。
所以想问问是否需要额外设置什么？

**Comment by nyanmisaka** [comment]
Check whether the dynamically loaded `libavcodec.so` is from the system built-in ffmpeg or the compiled ffmpeg-rockchip.
