### ISSUE TITLE
编码支持的颜色格式有哪些？

### ISSUE THREAD

**Issue by huochen1** [nyanmisaka/ffmpeg-rockchip#147]
请问一下，这个编码的颜色格式支持NV12,NV16,BGR3这三种颜色格式嘛

**Comment by nyanmisaka** [comment]
Yes.

https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Encoder

https://github.com/nyanmisaka/ffmpeg-rockchip/blob/b81c3bf1c40bbc34de3950451287fd4f5213bdd3/libavcodec/rkmppenc.c#L40-L93
