### ISSUE TITLE
编译opencv with ffmpeg 时出错

### ISSUE THREAD

**Issue by Grifcc** [nyanmisaka/ffmpeg-rockchip#18]
描述： 由于ffmpeg 5.0开始弃用了avcodec_get_context_defaults3，编译opencv时出错，导致编译失败
问题： 能否集成一个低版本的ffmpeg  version<5.0

**Comment by nyanmisaka** [comment]
There are currently no immediate plans to port to 5.1. You can try it yourself, it may take a while but it won't be too difficult.
