### ISSUE TITLE
更换了Armbian_23.11.1_Orangepi5-plus_bookworm_legacy_5.10.160.img后好像hevc 10解码失效了😭

### ISSUE THREAD

**Issue by leesonaa** [nyanmisaka/ffmpeg-rockchip#24]
**n大好!更换了底层系统后，我做了以下操作:**
1. 更新系统的操作
2. 下载了[libmali-valhall-g610-g13p0-x11-wayland-gbm_1.9-1_arm64.deb](https://github.com/tsukumijima/libmali-rockchip/releases/download/v1.9-1-3381696/libmali-valhall-g610-g13p0-x11-wayland-gbm_1.9-1_arm64.deb)
3. sudo apt install ./libmali-valhall-g610-g13p0-x11-wayland-gbm_1.9-1_arm64.deb
4. chmod -R 777 /dev
5. 之前也是同样的系统，同样的步骤，是可以解码的，但是这次不知道什么原因不行了。求指导😭

**出现的问题:**
  - 4k hevc sdr 的可以解码播放，4k hevc 10bit 解码转圈，3分钟播放1秒这样子(开启了色调映射)，不开色调映射可以点开就能解码
 
**docker日志和配置截图:** 

[_jellyfin_logs.txt](https://github.com/nyanmisaka/ffmpeg-rockchip/files/14151023/_jellyfin_logs.txt)

![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/59df96ce-a4b5-4523-ba90-a222afab0713)
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/3898011f-2991-4273-ad3b-3b5f9779cc2a)
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/f3c26432-b265-4e65-a32f-3816796c686e)
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/1d3e572f-0d2e-4127-91bf-60ec7f0c79f6)
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/31dcbd73-20d1-4365-9d03-b5d5819c5254)
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/97571961/433dee47-2865-4445-a25c-83015dd4517b)

**Comment by nyanmisaka** [comment]
For 5.10.160 kernel:
on host install [v1.9-1-2d267b0](https://github.com/tsukumijima/libmali-rockchip/releases/tag/v1.9-1-2d267b0)

For 6.1.43 kernel:
on host install [v1.9-1-3381696](https://github.com/tsukumijima/libmali-rockchip/releases/tag/v1.9-1-3381696)
