### ISSUE TITLE
lost the last frame in complex filter

### ISSUE THREAD

**Issue by mcerveny** [nyanmisaka/ffmpeg-rockchip#34]
Hello.
I found that complex filter (double RGA filter) lost the last frame. `in.ts` has 100 frames.
- single RGA filter (overlay or scale)
  - `./ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -i in.ts -i ovr.png -filter_complex '[0:v]hwupload[main];[1:v]hwupload[overlay];[main][overlay]overlay_rkrga=eof_action=repeat:repeatlast=true:format=nv12' -c:v h264_rkmpp out.ts -y` --> 100 frames
  -  `./ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -i in.ts  -filter_complex 'hwupload,scale_rkrga=w=1280:h=720' -c:v h264_rkmpp  out.ts -y` --> 100 frames
- double RGA filter (overlay and scale)
  - `./ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -i in.ts -i ovr.png -filter_complex '[0:v]hwupload[main];[1:v]hwupload[overlay];[main][overlay]overlay_rkrga=eof_action=repeat:repeatlast=true:format=nv12,scale_rkrga=w=1280:h=720' -c:v h264_rkmpp  out.ts -y` --> **99 frames**

**Comment by nyanmisaka** [comment]
Good catch. In my use case `overlay_rkrga` is always the last filter so I didn't notice this.

**Comment by nyanmisaka** [comment]
@mcerveny 27136b05e0742450a019d6bab80d840ac5fd6421 should fix this issue.

**Comment by mcerveny** [comment]
Yes ! resolved problem. Thank you.
