### ISSUE TITLE
解码后的图像颜色不对

### ISSUE THREAD

**Issue by szaipcljl** [nyanmisaka/ffmpeg-rockchip#43]
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/36354489/fc8aa3e3-f768-410d-a7ae-390e1e62c3d0)

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Video-Transcode

Use the ffmpeg command from the Wiki to verify your output.
If it works fine, look for the problem in the code you wrote yourself, not ffmpeg.

**Comment by szaipcljl** [comment]
ok，thanks。i try it with command line
