### ISSUE TITLE
Using with Photoprism

### ISSUE THREAD

**Issue by tredntredn** [nyanmisaka/ffmpeg-rockchip#46]
Hello
Is it possible to use compiled ffmpeg with Photoprism to encode videos?

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip/wiki

As long as you have experience using intel qsv, nVidia nvenc or similar hardware acceleration through ffmpeg, using this project will be simple. As for Photoprism, you need to ask its developers to adapt this.
