### ISSUE TITLE
use filter scale_rkrga failed in rk3588（ubuntu22.02 desktop）

### ISSUE THREAD

**Issue by gaop921766** [nyanmisaka/ffmpeg-rockchip#49]
cmd:
ffmpeg-rockchip-master$ ./ffmpeg -timeout 10000000 -rtsp_transport tcp -loglevel debug -c:v h264_rkmpp -i rtsp://xxx:xx@192.168.27.60/h264/ch2/main/av_stream -vf scale_rkrga=1280:720 -c:v h264_rkmpp -global_quality 19  -g 16 -rw_timeout 5000000 -f flv -an rtmp://127.0.0.1/cams/live
log:

[AVFilterGraph @ 0x556afe0190] Setting 'w' to value '1280'
[AVFilterGraph @ 0x556afe0190] Setting 'h' to value '720'
detected 8 logical cores
[graph 0 input from stream 0:0 @ 0x556af59940] Setting 'video_size' to value '1920x1080'
[graph 0 input from stream 0:0 @ 0x556af59940] Setting 'pix_fmt' to value '23'
[graph 0 input from stream 0:0 @ 0x556af59940] Setting 'time_base' to value '1/90000'
[graph 0 input from stream 0:0 @ 0x556af59940] Setting 'pixel_aspect' to value '0/1'
[graph 0 input from stream 0:0 @ 0x556af59940] Setting 'frame_rate' to value '25/1'
[graph 0 input from stream 0:0 @ 0x556af59940] w:1920 h:1080 pixfmt:nv12 tb:1/90000 fr:25/1 sar:0/1
[format @ 0x556af571d0] Setting 'pix_fmts' to value 'gray|yuv420p|yuv422p|yuv444p|nv12|nv21|nv16|nv24|yuyv422|yvyu422|uyvy422|rgb24|bgr24|rgba|rgb0|bgra|bgr0|argb|0rgb|abgr|0bgr|drm_prime'
[auto_scale_0 @ 0x556af57ec0] w:iw h:ih flags:'' interl:0
[Parsed_scale_rkrga_0 @ 0x556b0815d0] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_scale_rkrga_0'
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 0x556af7a8e0] Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
[vist#0:0/h264 @ 0x556af4c8a0] Decoder returned EOF, finishing
[vist#0:0/h264 @ 0x556af4c8a0] Terminating decoder thread
Error while filtering: Function not implemented
[out#0/flv @ 0x556af50cf0] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
[AVIOContext @ 0x556af58b90] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[rtmp @ 0x556af56660] UnPublishing stream...
[rtmp @ 0x556af56660] Deleting stream...
[in#0/rtsp @ 0x556af45fb0] Terminating demuxer thread
[in#0/rtsp @ 0x556af45fb0] Input file #0 (rtsp://admin:cue_1225@192.168.27.60/h264/ch2/main/av_stream):
[in#0/rtsp @ 0x556af45fb0]   Input stream #0:0 (video): 7 packets read (295283 bytes); 2 frames decoded; 0 decode errors;
[in#0/rtsp @ 0x556af45fb0]   Total: 7 packets (295283 bytes) demuxed
Conversion failed!
请问是什么原因啊
谢谢！

**Comment by nyanmisaka** [comment]
https://github.com/nyanmisaka/ffmpeg-rockchip/issues/47#issuecomment-2019893392

![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/14953024/eea77775-f0ef-4bf3-8c92-2c1fcb9a4296)
