### ISSUE TITLE
是否支持在RK3568上编解码？

### ISSUE THREAD

**Issue by jiephe** [nyanmisaka/ffmpeg-rockchip#67]
在RK3588上编译了之后，放到RK3568平台上运行，解码非常慢，掉帧严重，25帧的视频只能解出来18帧，请问是什么原因

**Comment by nyanmisaka** [comment]
Without a detailed description and logs I can't help.

Recommended video player configurations can be found in the [Wiki](https://github.com/nyanmisaka/ffmpeg-rockchip/wiki).
