### ISSUE TITLE
why do not support drawtext

### ISSUE THREAD

**Issue by yuyinw** [nyanmisaka/ffmpeg-rockchip#68]
I  installed libxml2-v2.9.14、fribidi-1.0.12、freetype-2.10.0、fontconfig-2.13.95

![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/42082530/6f2a1698-55b6-4abc-affd-d6b9858ca17f)

**Comment by nyanmisaka** [comment]
Building ffmpeg is non-trivial for beginners. You can use a pre-built binary instead.

https://github.com/MarcA711/Rockchip-FFmpeg-Builds/releases

**Comment by yuyinw** [comment]
thank you very much !!!  use Rockchip-FFmpeg-Builds  can work !

i have a question:   the drawtext   defaults to using CPU to overlay watermarks,   will we consider using GPU to add watermarks in the future

**Comment by nyanmisaka** [comment]
This is beyond what MPP/RGA runtime can support.

You can use the following command to achieve zero-copy, but the text will still be rendered by the CPU.

`-vf "scale_rkrga=format=nv12,hwmap,format=nv12,drawtext=...,hwmap"`

**Comment by xunfeng1980** [comment]
--enable-libharfbuzz ..............
