### ISSUE TITLE
addr = mpp_buffer_get_ptr(desc->buffers[i]); core dump

### ISSUE THREAD

**Issue by MapleAura** [nyanmisaka/ffmpeg-rockchip#7]
大佬您好，又来请教一个问题。

我在进行网络流解码或者文件解码操作时hwcontext_rkmpp.c:397出现了core dump。
命令行如下：
`gdb --args ffmpeg -re -c:v h264_rkmpp  -hwaccel_output_format drm_prime -i /xxx/8.mkv -an -sn -vframes 5000 -f null -`

堆栈：
![image](https://github.com/nyanmisaka/ffmpeg-rockchip/assets/149750728/11002a0b-9f62-4302-a2e2-84be10b249c9)

采用调用ffmpeg接口的方式出现了同样的问题，mpp已经更新到官网最新，使用的是最新的6.1分支的代码。

附件是我测试用的视频
[8.zip](https://github.com/nyanmisaka/ffmpeg-rockchip/files/13926859/8.zip)

**Comment by nyanmisaka** [comment]
@MapleAura 现在流出的6.1内核不是正式版，有很多bug，里面的dma-heap分配器没有移植有问题用不了，而mpp运行库写死了用/dev/dma_heap这个路径是否可读来检查dma-heaps是否可用，然而实际里面的设备不可用，所以就segfault了。

建议暂时换回5.10，或者用此补丁打在mpp运行库上。
https://github.com/nyanmisaka/mpp/commit/49b4fc71d25255b3005aa05f761bfd92b8c85e78

**Comment by nyanmisaka** [comment]
@MapleAura It was a regression. Please apply the latest commit 97e6a5e and try again.

**Comment by MapleAura** [comment]
> t was a regression

好了 结果能拿到了 谢谢您
