### ISSUE TITLE
-hwaccel rkmpp doesn't work

### ISSUE THREAD

**Issue by sztukai** [nyanmisaka/ffmpeg-rockchip#72]
Command:
ffmpeg -rtsp_transport tcp -hwaccel rkmpp -i "rtsp://admin:Admin707@192.168.1.64:554/h265/ch1/main/av_stream" -f rawvideo -pix_fmt bgr24 -max_muxing_queue_size 1024 /dev/null
Output:
frame=  224 fps= 34 q=-0.0 Lsize= 1360800kB time=00:00:08.92 bitrate=1249739.2kbits/s dup=48 drop=1 speed=1.35x
top displays ffmpeg's CPU usage as 200%

Environment:
Cannot access '/dev/iep': No such file or directory
Cannot access '/dev/vpu_service': No such file or directory
Cannot access '/dev/hevc_service': No such file or directory
Cannot access '/dev/rkvdec': No such file or directory
Cannot access '/dev/rkvenc': No such file or directory
Cannot access '/dev/vepu': No such file or directory
Cannot access '/dev/h265e': No such file or directory

kernel：
5.10.160

**Comment by sztukai** [comment]
Thank you for your response. After running the command you provided, I encountered the following error. Is my environment missing some kernels?

root@linux:/home/zysj-sz/Downloads# ffmpeg -rtsp_transport tcp -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -i "rtsp://admin:Admin707@192.168.1.64:554/h265/ch1/main/av_stream" -vf “scale_rkrga=format=bgr24,hwmap,format=bgr24” -f rawvideo -max_muxing_queue_size 1024 /dev/null
ffmpeg version 2093e2b Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
  configuration: --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, rtsp, from 'rtsp://admin:Admin707@192.168.1.64:554/h265/ch1/main/av_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
[AVFilterGraph @ 0x5599a4ca80] No such filter: '“scale_rkrga'
[vost#0:0/rawvideo @ 0x55998f6b80] Error initializing a simple filtergraph
Error opening output file /dev/null.
Error opening output files: Filter not found

**Comment by nyanmisaka** [comment]
Try this again.
```
ffmpeg -rtsp_transport tcp -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -i "rtsp://admin:Admin707@192.168.1.64:554/h265/ch1/main/av_stream" -vf "scale_rkrga=format=bgr24,hwmap,format=bgr24" -f rawvideo -max_muxing_queue_size 1024 /dev/null
```

**Comment by sztukai** [comment]
Thank you for your help. The problem has been resolved.
