### ISSUE TITLE
difference between h264_rkmpp and hevc_rkmpp

### ISSUE THREAD

**Issue by ZH-1225** [nyanmisaka/ffmpeg-rockchip#75]
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v hevc_rkmpp -c:a copy h264_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v hevc_rkmpp -c:a copy hevc_rkmpp.mp4
I used two commands to find that the generated MP4 files were about the same size

**Comment by Tryanks** [comment]
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v **hevc_rkmpp** -c:a copy h264_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v **hevc_rkmpp** -c:a copy hevc_rkmpp.mp4

**Comment by ZH-1225** [comment]
> 制 h264

./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v h264_rkmpp -c:a copy h264_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v hevc_rkmpp -c:a copy hevc_rkmpp.mp4

**Comment by ZH-1225** [comment]
> both using same encoder hevc_rkmpp (-c:v hevc_rkmpp )

./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v h264_rkmpp -c:a copy h264_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v hevc_rkmpp -c:a copy hevc_rkmpp.mp4

thanks!

**Comment by ZH-1225** [comment]
> ./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v **hevc_rkmpp** -c:a copy h264_rkmpp.mp4 ./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v **hevc_rkmpp** -c:a copy hevc_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v h264_rkmpp -c:a copy h264_rkmpp.mp4
./ffmpeg -i /home/pi/Videos/test_ffmpeg.mp4 -c:v hevc_rkmpp -c:a copy hevc_rkmpp.mp4

thanks!

**Comment by nyanmisaka** [comment]
You have to set the bitrate or quality factor manually, otherwise the default bitrate of rkmpp encoders is 2000k.

https://github.com/nyanmisaka/ffmpeg-rockchip/blob/9efe5bcff082d6538702d01c9b7126f40da27361/libavcodec/rkmppenc.h#L245
