### ISSUE TITLE
Generic error in external library

### ISSUE THREAD

**Issue by njuyuejk** [nyanmisaka/ffmpeg-rockchip#79]
我按照之前的解决方案，重新编译安装了mpp。依旧还是不行

**Comment by nyanmisaka** [comment]
Please provide the SOC name, RK Linux kernel version, and where you obtained the MPP from(MPP commit/version info).

**Comment by njuyuejk** [comment]
> Please provide the SOC name, RK Linux kernel version, and where you obtained the MPP from(MPP commit/version info).
这个问题已经解决了。
