### ISSUE TITLE
运行时出现

### ISSUE THREAD

**Issue by tu-nie** [nyanmisaka/ffmpeg-rockchip#82]

**Comment by tu-nie** [comment]
/usr/include/libavfilter/avfilter.h:566:5: error: ‘AVChannelLayout’ does not name a type; did you mean ‘AVFilterChannelLayouts’?
  566 |     AVChannelLayout ch_layout;  ///< channel layout of current buffer (see libavutil/channel_layout.h)
      |     ^~~~~~~~~~~~~~~
      |     AVFilterChannelLayouts

**Comment by nyanmisaka** [comment]
Please make sure your project is compatible with FFmpeg 6.0+.
