### ISSUE TITLE
Decoder h264 does not support device type rkmpp.

### ISSUE THREAD

**Issue by jinjie412** [nyanmisaka/ffmpeg-rockchip#91]
./hw_decode rkmpp /home/topeet/1663126597137_dkbgl.mp4 output.yuv
Decoder h264 does not support device type rkmpp.

./ffmpeg -decoders | grep rkmpp
ffmpeg version 8164ff7 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=./ffm_install --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
 V..... av1_rkmpp            Rockchip MPP (Media Process Platform) AV1 decoder (codec av1)
 V..... h263_rkmpp           Rockchip MPP (Media Process Platform) H263 decoder (codec h263)
 V..... h264_rkmpp           Rockchip MPP (Media Process Platform) H264 decoder (codec h264)
 V..... hevc_rkmpp           Rockchip MPP (Media Process Platform) HEVC decoder (codec hevc)
 V..... mpeg1_rkmpp          Rockchip MPP (Media Process Platform) MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_rkmpp          Rockchip MPP (Media Process Platform) MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_rkmpp          Rockchip MPP (Media Process Platform) MPEG4 decoder (codec mpeg4)
 V..... vp8_rkmpp            Rockchip MPP (Media Process Platform) VP8 decoder (codec vp8)
 V..... vp9_rkmpp            Rockchip MPP (Media Process Platform) VP9 decoder (codec vp9)

why run  ./hw_decode rkmpp /home/topeet/output.mp4 output.yuv
error
Decoder h264 does not support device type rkmpp.

**Comment by nyanmisaka** [comment]
The `hw_decode` sample [only supports](https://github.com/nyanmisaka/ffmpeg-rockchip/commit/1e0c75ea165c926c544d42f0a1e51d7f6fa95354) hw accelerators such as `vaapi/cuda/vulkan/dxva2/d3d11va/d3d12va`, not `qsv/cuvid/rkmpp`.

See also https://github.com/nyanmisaka/ffmpeg-rockchip/wiki/Decoder
